"""Conteúdo das fichas de módulo de Cidadania e Desenvolvimento (10.º ano, 2026/2027).

Campos marcados «A definir» dependem do horário e do calendário da turma
(ver _interno/01-sistema/HORARIO.md e CALENDARIO.md).
"""

COMUM = {
    "curso": "Interpretação",
    "turma": "INTP26",
    "professor": "Pedro Fernandes",
    "ano_letivo": "2026/2027",
    "disciplina": "Cidadania e Desenvolvimento",
    "recuperacao": [
        "**1ª Recuperação – Reformulação e reentrega dos trabalhos previstos no processo de avaliação do módulo, com defesa oral individual (10 minutos).",
        "",
        "** 2ª Recuperação – Trabalho individual de projeto sobre um tema do módulo, com defesa oral.",
        "",
        "** Recuperação Época Especial – Trabalho individual de projeto sobre um tema do módulo, com defesa oral.",
        "",
        "Não há testes escritos: todas as modalidades de avaliação e de recuperação são por projeto.",
    ],
}

RECURSOS_BASE = [
    "Sem manual adotado. Materiais do professor (diapositivos, fichas do aluno, diário de bordo).",
    "Direção-Geral da Educação – Estratégia Nacional de Educação para a Cidadania, 2017.",
    "Direção-Geral da Educação – Perfil dos Alunos à Saída da Escolaridade Obrigatória, 2017.",
    "Declaração Universal dos Direitos Humanos (ONU, 1948), versão portuguesa.",
    "Constituição da República Portuguesa.",
]

REC_SALA = ["- Computador;", "- Projetor;", "- Ficha do aluno."]
REC_ESTUDIO = ["- Sala livre de mesas;", "- Projetor."]
REC_PROJETO = ["- Computador;", "- Internet;", "- Sala livre de mesas."]

MODULO_1 = {
    "ficheiro": "CD_MOD_1_Ser-se_Humano_{turma}_2026_2027.docx",
    "titulo": "Módulo 1 – Ser-se humano: investigação e informação",
    "horas": "30",
    "inicio": "A definir",
    "fim": "A definir",
    "faltas": "6",
    "conteudos": [
        (["**Módulo 1 – Ser-se humano: investigação e informação",
          "O que nos torna humanos: dignidade, razão, consciência e relação com os outros. Declaração Universal dos Direitos Humanos (art. 1.º) e Constituição da República Portuguesa (art. 1.º e 13.º). Primeira verificação de afirmações. Apresentação do módulo e do projeto."],
         "4h", REC_SALA),
        (["Direitos humanos no quotidiano: direitos, deveres, violações e mecanismos de proteção.",
          "Igualdade e não discriminação; igualdade de género."],
         "4h", REC_SALA),
        (["Interculturalidade: identidade, pertença, estereótipo e preconceito.",
          "Oficina de expressão dramática «O outro lado»: improvisação a partir de posições sorteadas."],
         "3h", REC_ESTUDIO),
        (["Como sabemos o que sabemos: pergunta, hipótese, evidência e conclusão.",
          "Facto, opinião e inferência."],
         "3h", REC_SALA),
        (["Informação e desinformação: tipos de fonte, autoria, data e intenção.",
          "Laboratório de verificação: leitura lateral, pesquisa inversa de imagens, verificação de citações e de números. Viés de confirmação."],
         "5h", ["- Computador;", "- Internet;", "- Projetor."]),
        (["Ética da investigação: consentimento informado, anonimato e proteção de dados.",
          "Técnicas de recolha: entrevista, inquérito e observação."],
         "2h", REC_SALA),
        (["Projeto «Pergunta Humana»: definição da pergunta, plano, recolha e verificação de informação, dossiê de investigação."],
         "5h", REC_PROJETO),
        (["Projeto «Pergunta Humana»: do material recolhido ao teatro-documento (seleção, montagem, ensaio); apresentação pública e debate."],
         "3h", REC_ESTUDIO),
        (["1ª Recuperação."], "1h", ["N/A"]),
    ],
    "atividades": [
        (["Oficina de expressão dramática «O outro lado»: improvisação a partir de posições sorteadas sobre identidade e preconceito.", ""], "3h / aula"),
        (["Laboratório de verificação: investigar e classificar afirmações que circulam online (verdadeiro, falso, enganador, sem prova).", ""], "3h / aula"),
        (["Apresentação pública do teatro-documento «Pergunta Humana», seguida de debate com o público.", ""], "3h / aula"),
    ],
    "projeto": (
        ["Projeto «Pergunta Humana»: investigação em grupo sobre uma pergunta acerca do que é ser-se humano, com dossiê de fontes verificadas e entrevistas com consentimento, apresentada como teatro-documento de 5 a 8 minutos."],
        "8h",
    ),
    "programa": [
        "**Módulo 1 – Ser-se humano: investigação e informação",
        "** Ser-se humano:",
        "~- Dignidade humana: razão, consciência e relação com os outros.",
        "~- Declaração Universal dos Direitos Humanos (1948) e Constituição da República Portuguesa: dignidade e igualdade.",
        "~- Direitos humanos no quotidiano: direitos, deveres e mecanismos de proteção.",
        "~- Igualdade e não discriminação; igualdade de género.",
        "~- Interculturalidade: identidade, pertença, estereótipo e preconceito.",
        "",
        "**Investigação e informação:",
        "~- Pergunta, hipótese, evidência e conclusão.",
        "~- Facto, opinião e inferência.",
        "~- Fontes: tipo, autoria, data e intenção.",
        "~- Desinformação: como circula e como se verifica (leitura lateral, pesquisa inversa de imagens, verificação de citações e de números).",
        "~- Viés de confirmação.",
        "~- Ética da investigação: consentimento informado, anonimato e proteção de dados.",
        "",
        "**Direitos Humanos | Igualdade de Género | Interculturalidade | Media",
        "",
        "**Projeto:",
        "~- «Pergunta Humana»: investigação em grupo e teatro-documento.",
    ],
    "objetivos": [
        "- Reconhecer a dignidade humana como fundamento dos direitos humanos.",
        "- Relacionar direitos e deveres da Declaração Universal dos Direitos Humanos e da Constituição com situações do quotidiano.",
        "- Identificar estereótipos e preconceitos e argumentar a favor da igualdade e da não discriminação.",
        "- Formular perguntas de investigação e distinguir facto, opinião e inferência.",
        "- Avaliar a credibilidade das fontes e verificar a informação antes de a partilhar.",
        "- Recolher informação respeitando a ética da investigação e a proteção de dados.",
        "- Comunicar os resultados de uma investigação numa criação artística fundamentada.",
    ],
    "perfil": (
        [
            "Estratégia Nacional de Educação para a Cidadania",
            "Direitos Humanos; Igualdade de Género; Interculturalidade; Media.",
            "",
            "Perfil dos Alunos à Saída da Escolaridade Obrigatória",
            "Áreas de competência: A – Linguagens e textos; B – Informação e comunicação; D – Pensamento crítico e pensamento criativo; E – Relacionamento interpessoal; F – Desenvolvimento pessoal e autonomia.",
            "",
            "Valores: Cidadania e participação; Liberdade; Responsabilidade e integridade.",
        ],
        [
            "**Direitos Humanos",
            "~Reconhecer a dignidade humana e os direitos que dela decorrem.",
            "~Identificar situações de violação de direitos e os mecanismos de proteção.",
            "",
            "**Igualdade e Interculturalidade",
            "~Identificar estereótipos e preconceitos e os seus efeitos.",
            "~Respeitar a diferença e valorizar a diversidade.",
            "",
            "**Media",
            "~Pesquisar, selecionar e avaliar informação de fontes diversas, verificando a sua credibilidade.",
            "~Distinguir facto, opinião e desinformação.",
            "",
            "**Investigação",
            "~Formular uma pergunta, planear a recolha e fundamentar conclusões em evidências.",
            "~Respeitar a ética da investigação: consentimento, anonimato, identificação das fontes.",
            "",
            "**Comunicação e criação",
            "~Transformar os resultados de uma investigação numa criação artística e defendê-la em público.",
        ],
        [
            "Diário de investigação (registo individual, aula a aula).",
            "",
            "Laboratório de verificação: verificação fundamentada de três afirmações.",
            "",
            "Dossiê de investigação «Pergunta Humana»: pergunta, plano, fontes verificadas, entrevistas com consentimento.",
            "",
            "Teatro-documento (5 a 8 minutos) e debate com o público.",
        ],
    ),
    "ponderacao": [
        ("Diário de investigação (registo individual, aula a aula).", "20%"),
        ("Laboratório de verificação: verificação fundamentada de três afirmações.", "20%"),
        ("Dossiê de investigação «Pergunta Humana» (grupo, com contributo individual identificado).", "30%"),
        ("Teatro-documento: apresentação pública e defesa das escolhas.", "30%"),
    ],
    "facultativos": [
        "Sentido responsabilidade",
        "Autoconsciência",
        "Trabalho de equipa",
        "Consciência social",
        "Informação e comunicação",
        "Pensamento crítico",
    ],
    "recursos": RECURSOS_BASE + [
        "Plataformas portuguesas de verificação de factos (ex.: Polígrafo; Observador Fact Check).",
    ],
}

MODULO_2 = {
    "ficheiro": "CD_MOD_2_Expressao_Algoritmos_{turma}_2026_2027.docx",
    "titulo": "Módulo 2 – Expressão: os algoritmos, criação e expressão",
    "horas": "30",
    "inicio": "A definir",
    "fim": "A definir",
    "faltas": "6",
    "conteudos": [
        (["**Módulo 2 – Expressão: os algoritmos, criação e expressão",
          "O que é um algoritmo: entrada, regras e saída. «Feed de papel»: simulação de um algoritmo de recomendação. Liberdade de expressão (DUDH, art. 19.º). Apresentação do módulo e do projeto."],
         "3h", REC_ESTUDIO),
        (["Liberdade de expressão e de criação: DUDH (art. 19.º) e Constituição da República Portuguesa (art. 37.º e 42.º).",
          "Limites: dignidade, discurso de ódio, difamação."],
         "4h", REC_SALA),
        (["Algoritmos de recomendação: dados, perfis e personalização.",
          "Bolhas de filtro, câmaras de eco e economia da atenção. Oficina «Diário de um feed»."],
         "5h", REC_SALA),
        (["Criação e inteligência artificial: autoria, direitos de autor, imitação de voz e de imagem, deepfakes, transparência."],
         "4h", ["- Computador;", "- Internet;", "- Projetor."]),
        (["Participação e segurança no espaço digital: discurso de ódio e ciberbullying; denunciar, moderar, proteger os outros; direitos dos utilizadores das plataformas."],
         "3h", REC_SALA),
        (["Projeto «Contra-feed»: pesquisa, conceito, guião e ensaios."],
         "8h", REC_PROJETO),
        (["Projeto «Contra-feed»: mostra pública e manifesto de uso da turma."],
         "2h", REC_ESTUDIO),
        (["1ª Recuperação."], "1h", ["N/A"]),
    ],
    "atividades": [
        (["«Feed de papel»: simulação física de um algoritmo de recomendação.", ""], "1h40 / aula"),
        (["Oficina «Diário de um feed»: registo e análise, durante uma semana, do que as plataformas mostram a cada aluno (sem dados pessoais).", ""], "2h / aula"),
        (["Mostra pública «Contra-feed» e apresentação do manifesto de uso da turma.", ""], "2h / aula"),
    ],
    "projeto": (
        ["Projeto «Contra-feed»: criação de uma performance ou vídeo-performance que torna visível o modo como um algoritmo molda o que vemos, dizemos ou criamos, acompanhada de um manifesto de uso da turma."],
        "10h",
    ),
    "programa": [
        "**Módulo 2 – Expressão: os algoritmos, criação e expressão",
        "** Algoritmos:",
        "~- O que é um algoritmo: entrada, regras e saída.",
        "~- Algoritmos de recomendação: dados, perfis e personalização.",
        "~- Bolhas de filtro e câmaras de eco.",
        "~- Economia da atenção e design persuasivo.",
        "",
        "**Criação e expressão:",
        "~- Liberdade de expressão e de criação (DUDH, art. 19.º; Constituição, art. 37.º e 42.º).",
        "~- Limites: dignidade, discurso de ódio, difamação.",
        "~- Criação com inteligência artificial: autoria, direitos de autor, deepfakes, transparência.",
        "~- Participação e segurança: denunciar, moderar, proteger os outros.",
        "",
        "**Media | Direitos Humanos | Instituições e participação democrática",
        "",
        "**Projeto:",
        "~- «Contra-feed»: performance ou vídeo-performance e manifesto de uso.",
    ],
    "objetivos": [
        "- Explicar o que é um algoritmo e como os algoritmos de recomendação selecionam o que vemos.",
        "- Reconhecer efeitos da personalização: bolhas de filtro, câmaras de eco e captura da atenção.",
        "- Conhecer a liberdade de expressão e de criação e os seus limites legais e éticos.",
        "- Discutir autoria, direitos de autor e transparência na criação com inteligência artificial.",
        "- Agir de forma segura e responsável no espaço digital: denunciar, moderar, proteger os outros.",
        "- Criar uma peça artística que torne visível o funcionamento de um algoritmo e defendê-la em público.",
    ],
    "perfil": (
        [
            "Estratégia Nacional de Educação para a Cidadania",
            "Media; Direitos Humanos; Instituições e participação democrática.",
            "",
            "Perfil dos Alunos à Saída da Escolaridade Obrigatória",
            "Áreas de competência: B – Informação e comunicação; C – Raciocínio e resolução de problemas; D – Pensamento crítico e pensamento criativo; H – Sensibilidade estética e artística; I – Saber científico, técnico e tecnológico.",
            "",
            "Valores: Liberdade; Responsabilidade e integridade; Curiosidade, reflexão e inovação.",
        ],
        [
            "**Algoritmos",
            "~Descrever um algoritmo em termos de entrada, regras e saída.",
            "~Explicar como a personalização pode reduzir a diversidade do que vemos.",
            "",
            "**Liberdade de expressão",
            "~Distinguir liberdade de expressão de discurso de ódio e de difamação, com base na lei.",
            "~Argumentar sobre quem decide o que é visto e ouvido no espaço digital.",
            "",
            "**Criação",
            "~Identificar questões de autoria e de direitos de autor em criações com inteligência artificial.",
            "~Assumir a transparência sobre as ferramentas usadas numa criação.",
            "",
            "**Participação",
            "~Conhecer mecanismos de denúncia e de proteção nas plataformas.",
            "~Criar e apresentar em público uma peça com intenção cívica.",
        ],
        [
            "Diário de um feed (registo individual e análise).",
            "",
            "Análise crítica de um caso (liberdade de expressão ou criação com inteligência artificial).",
            "",
            "Processo do projeto «Contra-feed»: conceito, guião, ensaios.",
            "",
            "Mostra pública e manifesto de uso da turma.",
        ],
    ),
    "ponderacao": [
        ("Diário de um feed (registo individual e análise).", "20%"),
        ("Análise crítica de um caso (liberdade de expressão ou criação com inteligência artificial), oral ou escrita.", "20%"),
        ("Projeto «Contra-feed»: processo (conceito, guião, ensaios).", "30%"),
        ("Projeto «Contra-feed»: mostra pública e manifesto de uso.", "30%"),
    ],
    "facultativos": [
        "Trabalho de equipa",
        "Consciência social",
        "Ferramentas digitais",
        "Pensamento crítico",
        "Sensibilidade estética",
        "Criatividade e inovação",
    ],
    "recursos": RECURSOS_BASE + [
        "Regulamento (UE) 2022/2065 – Regulamento dos Serviços Digitais.",
        "Código do Direito de Autor e dos Direitos Conexos.",
    ],
}

MODULOS = [MODULO_1, MODULO_2]
